### ISSUE TITLE
not work with idea 2023.1 eap 4

### ISSUE THREAD

**Issue by towith** [dkandalov/live-plugin#156]
Thanks for your wonderful plugin.
It can not load in 2023.1 eap 4, 
stacktrace here:

```
Loading error: my-ide-actions-kt

com.intellij.diagnostic.PluginException: Error while loading plugin class.
java.lang.NoSuchMethodError: 'void com.intellij.util.lang.UrlClassLoader.<init>(java.util.List, com.intellij.util.lang.ClassPath)'
	at liveplugin.implementation.pluginrunner.PluginClassLoader_Fork.<init>(PluginClassLoader_Fork.java:167)
	at liveplugin.implementation.pluginrunner.PluginDependencies.createClassLoaderWithDependencies(PluginRunner.kt:80)
	at liveplugin.implementation.pluginrunner.kotlin.KotlinPluginRunner.setup(KotlinPluginRunner.kt:83)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt$runWith$1.invoke(PluginRunner.kt:161)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt.runInBackground$lambda$2(PluginRunner.kt:171)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:250)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833) [Plugin: LivePlugin]
	at liveplugin.implementation.common.IdeUtil.displayError(ide-util.kt:68)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt.displayError(PluginRunner.kt:187)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt$runWith$1.invoke(PluginRunner.kt:163)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt.runInBackground$lambda$2(PluginRunner.kt:171)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:250)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by dkandalov** [comment]
Thank you for reporting the issue.
I just uploaded v0.8.5beta which (once approved) should fix the issue.

https://github.com/dkandalov/live-plugin/releases/tag/v0.8.5beta

**Comment by towith** [comment]
Great, thanks 👍

**Comment by sirnple** [comment]
I also met the similar issue, this is my stacktrace:
```java
Error while loading plugin class.
java.lang.NoSuchMethodError: 'void com.intellij.util.lang.ClassPath.<init>(java.util.List, com.intellij.util.lang.UrlClassLoader$Builder, java.util.function.Function, boolean)'
	at liveplugin.implementation.pluginrunner.PluginDependencies.createClassLoaderWithDependencies(PluginRunner.kt:82)
	at liveplugin.implementation.pluginrunner.kotlin.KotlinPluginRunner.setup(KotlinPluginRunner.kt:83)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt$runWith$1.invoke(PluginRunner.kt:161)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt$runInBackground$2.run(PluginRunner.kt:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dkandalov** [comment]
@sirnple thank you for reporting the stacktrace!
Unfortunately, it's yet another issue (fixed in this commit [#191c2556](https://github.com/dkandalov/live-plugin/commit/191c255624a503952aff29cf129e16023f8ac1e8))

I uploaded version 0.8.6 which should be available once approved by jetbrains.

**Comment by dkandalov** [comment]
I'll close the issue because I believe the plugin now works in EAP 🙈
